name: Integration

on: [pull_request]

jobs:
  API_Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        - run: npm install -g newman
        - run: newman run mycollection.json -e env.json --reporter-html-export newman
